Feature/personas
pAI-OS/paios pull request #5
Opened 2024-07-23 17:18 UTC by AnniePachecoJ

# Summary
This PR modifies the object Persona and PersonaCreate, changing the fields voiceId to Voice object and faceId to Face object

 
# Changes
 
- [x] Added Voice schema
- [x] Added Face schema
- [x] Modified Persona
- [x] Modified PersonaCreate

 
# Related Issues
N/A
 
# Type of Change
This change solved the comments posted on the review of the previous PR created by @rquesada [https://github.com/pAI-OS/paios/pull/4]
 
# Checklist 
- [x] I have read the [CONTRIBUTING](https://github.com/pAI-OS/paios/blob/main/CONTRIBUTING.md) documentation.
- [x]  I have performed a self-review of my own code.
- [x]  I have added tests that prove my fix is effective or that my feature works.
- [x]  I have updated the documentation (if applicable).
 
# Screenshots (if applicable)
![image](https://github.com/user-attachments/assets/02e7d59c-c4a3-41e9-b0fb-4558fe0a2187)
![image](https://github.com/user-attachments/assets/7f69c26d-0aee-4e88-af17-7e0944afac8f)
![image](https://github.com/user-attachments/assets/566ebfdd-8f03-4e3c-9cfa-19caf7d9e060)
 
 
# Additional Context
Tested locally using Swagger.

2024-07-25 16:32 UTC, quaid requested changes
Hey @AnniePachecoJ thanks for the review request, happy to do what I can.

Since I'm not (yet) familiar with the project coding standards and I'm not a programmer, there's not much I have to say about the code changes. It doesn't look like you added any tests, documentation, or many additional comments in the code itself? For many projects I'd expect to see signs of test driven development and docs or code comments similar to the "Additional Context" in the PR template. But I'm not blocking on those, and I don't know if those are blockers.

For the change I'm requesting, I may be incorrect so please let me know, but GitHub is marking the PR as blocked because the commit was not signed. IIUC, you can create and self-sign a GPG key, then configure git locally and GitHub to use sign your commit, and that should be sufficient. All of the steps with keysigning and so forth shouldn't be part of the signing of the commit, rather those are part of building the web of trust within the project.

Here's the link GH gives from the blocked merge area:

https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

2024-07-25 21:50 UTC, rquesada requested changes
Add some feedback

2024-07-25 21:50 UTC, rquesada commented on apis/paios/openapi.yaml
> +    Voice:
Remove Voice schema, it is unused

2024-07-25 21:50 UTC, rquesada commented on apis/paios/openapi.yaml
> +    Face:
Remove Face schema, it is unused

2024-07-25 21:50 UTC, rquesada commented on backend/api/PersonasView.py
> +        return JSONResponse(persona.dict(), status_code=200)
add validation if person is None like:

```
if persona is None:
     return JSONResponse({"error": "Persona not found"}, status_code=404)
return JSONResponse(persona.dict(), status_code=200)
```

2024-07-25 21:50 UTC, rquesada commented on backend/api/PersonasView.py
>          await self.pm.delete_persona(id)
Add Validation:
```
success = await self.am.delete_persona(id)
if not success:
      return JSONResponse({"error": "Persona not found"}, status_code=404)
```

2024-07-25 21:50 UTC, rquesada commented on backend/managers/PersonasManager.py
> +            stmt = update(Persona).where(Persona.id == id).values(**persona_data)
add validation:
```
result = await session.execute(stmt)
if result.rowcount > 0:                
      await session.commit()
      updated_persona = await session.get(Persona, id)
      return PersonaSchema(id=updated_persona.id, **persona_data)
return None
```

2024-07-25 21:50 UTC, rquesada commented on backend/managers/PersonasManager.py
>              await session.commit()
Add:
```
await session.commit()
return result.rowcount > 0
```

2024-07-25 21:50 UTC, rquesada commented on backend/managers/PersonasManager.py
>      async def retrieve_personas(self, offset=0, limit=100, sort_by=None, sort_order='asc', filters=None):
Add a return value:
```
async def retrieve_personas(self, offset:int = 0, limit:int = 100, sort_by:Optional[str] = None, sort_order:str = 'asc',  [filters=None](filters: Optional[Dict[str, Any]] = None)): -> Tuple[List[PersonaSchema], int]
```

2024-07-25 21:50 UTC, rquesada commented on backend/managers/PersonasManager.py
>      async def update_persona(self, id: str, persona_data: PersonaCreateSchema):
add a return value:
```
async def update_persona(self, id: str, persona_data: PersonaCreateSchema): -> Optional[PersonaSchema]
```

2024-07-25 21:50 UTC, rquesada commented on backend/managers/PersonasManager.py
add return value:
```
async def delete_persona(self, id): -> bool
```

2024-07-25 21:50 UTC, rquesada commented on backend/managers/PersonasManager.py
> +    async def retrieve_persona(self, id:str) -> PersonaSchema:
Fix return value:
```
async def retrieve_persona(self, id:str) -> Optional[PersonaSchema]:
```

2024-07-25 21:50 UTC, rquesada commented on backend/models.py
> +class Voice(Base):
Remove unused Voice model

2024-07-25 21:50 UTC, rquesada commented on backend/models.py
> +class Face(Base):
Remove unused Face model

2024-07-25 21:50 UTC, rquesada commented on backend/schemas.py
> +
remove unused class:
-VoiceBaseSchema
-VoiceCreateSchema
-VoiceSchema
-FaceBaseSchema
-FaceCreateSchema
-FaceSchema

2024-07-26 18:57 UTC, AnniePachecoJ commented
This PR has to be deleted because there were some commits which were unverified

2024-07-26 18:57 UTC, closed without merging